export const VIEW_SIGNIN = 'VIEW_SIGNIN';
export const VIEW_SIGNUP = 'VIEW_SIGNUP';
export const VIEW_PROFILE = 'VIEW_PROFILE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const MODAL_CANCEL = 'MODAL_CANCEL';